server:
  port: 8081

spring:
  profiles: default
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        productChanged-in:
          group: product
          destination: shop
          contentType: application/json
        productChanged-out:
          destination: shop
          contentType: application/json
        productExcept-in:
          group: product
          destination: except
          contentType: application/json
        productExcept-out:
          destination: except
          contentType: application/json
        orderCreated-in:
          group: order
          destination: orders
          contentType: application/json
        orderCreated-out:
          destination: orders
          contentType: application/json

---

server:
  port: 8080

spring:
  profiles: docker
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        productChanged-in:
          group: product
          destination: shop
          contentType: application/json
        productChanged-out:
          destination: shop
          contentType: application/json
        productExcept-in:
          group: product
          destination: except
          contentType: application/json
        productExcept-out:
          destination: except
          contentType: application/json
        orderCreated-in:
          group: order
          destination: orders
          contentType: application/json
        orderCreated-out:
          destination: orders
          contentType: application/json